name: flutterflow_colorpicker
description: HSV(HSB)/HSL/RGB/Material color picker for use in FlutterFlow projects.
version: 0.0.1
homepage: https://github.com/mchome/flutterflow_colorpicker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
